<a href="https://colab.research.google.com/github/Sinshyrajesh/AI_ML_COURSE_ICTAK_SINSHY/blob/main/Numpy_and_Pandas_Practice_problems.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy and Pandas Practice problems

1.	Create an array of numbers from 1 to 20 and reshape it into a 4×5 matrix.

In [3]:
import numpy as np


In [21]:
array= np.arange(1,21)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
array = np.reshape(array,(4,5))
array

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

2.	Create an array of 10 zeros and replace the 5th element with 100.

In [26]:
 a= np.zeros(10)
 a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
a[4]=100
a

array([  0.,   0.,   0.,   0., 100.,   0.,   0.,   0.,   0.,   0.])

3.	Create a NumPy array of even numbers between 2 and 40."

In [17]:
even = np.arange(2,41,2)
even

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40])

4.	Generate a 1D array of 15 random integers between 1 and 100 and find its min, max, mean, and standard deviation.

In [28]:
rand_int = np.random.randint(1, 101, 15)
rand_int


array([100,   8,  53,  81,  64,  74,  81,  97,  30,  82,  76,  46,   2,
        74,  98])

In [29]:
rand_int.min()


np.int64(2)

In [30]:
rand_int.max()

np.int64(100)

In [31]:
rand_int.mean()

np.float64(64.4)

In [32]:
rand_int.std()

np.float64(29.850293130889014)

5.	Given two arrays of sales and costs, calculate profit and profit percentage arrays.

In [47]:
sales = np.array([2000, 3000, 2500, 4000])
costs = np.array([1200, 1500, 1300, 3000])
profit = sales-costs
profit

array([ 800, 1500, 1200, 1000])

In [49]:
profit_percent = (profit/sales) * 100
profit_percent

array([40., 50., 48., 25.])

6.	Create a 6×6 random matrix and compute row sums, column sums, and total sum.

In [51]:
mat = np.random.randint(1, 50, (6, 6))
mat


array([[29, 13, 35, 44, 30, 15],
       [29, 37, 11, 27, 17, 24],
       [ 2, 21, 18, 25,  8, 10],
       [40, 29, 26, 25, 44, 37],
       [16,  9, 38, 14, 24, 14],
       [ 4, 18, 16,  5, 10, 48]])

In [66]:
print("Row sums:" ,mat.sum(axis=1))


Row sums: [166 145  84 201 115 101]


In [68]:
print("Column sum:" , mat.sum(axis=0))


Column sum: [120 127 144 140 133 148]


In [69]:
print(" total sum:" , mat.sum())

 total sum: 812


7.	Given stock prices, compute daily returns using vectorized NumPy operations.

In [83]:
prices = np.array([100, 102, 101, 105, 110])
returns = (prices[1:]- prices[:-1]) / prices[:-1]
print("Stock Prices:", prices)
print("Daily Returns:",returns.round(4))

Stock Prices: [100 102 101 105 110]
Daily Returns: [ 0.02   -0.0098  0.0396  0.0476]


8.	Convert an array of annual interest rates into monthly rates using vectorization.

In [84]:
annual_rates = np.array([0.12, 0.10, 0.15])
monthly_rates = annual_rates / 12
print("Annual Interest Rates:", annual_rates)
print("Monthly Interest Rates:", monthly_rates.round(3))

Annual Interest Rates: [0.12 0.1  0.15]
Monthly Interest Rates: [0.01  0.008 0.012]


9.	Normalize a given array of portfolio weights so that the sum becomes 1.

In [88]:
weights = np.array([20, 35, 40,50])
normalized = weights / weights.sum()
print("Original weights:", weights)
print("Normalized (sum=1):", normalized.round(4))

Original weights: [20 35 40 50]
Normalized (sum=1): [0.1379 0.2414 0.2759 0.3448]


10.	Create a Pandas Series from the following list: [1200, 1500, 1800, 2000, 2200]

a.	Find:

i.	mean

ii.	max

iii.	index of the max value


In [94]:
import pandas as pd

data = [1200, 1500, 1800, 2000, 2200]
s = pd.Series(data, index=['Jan', 'Feb', 'Mar', 'Apr', 'May'])
print("Series:\n", s)
print("Mean:", s.mean())
print("Max:", s.max())
print("Index of max:", s.idxmax())



Series:
 Jan    1200
Feb    1500
Mar    1800
Apr    2000
May    2200
dtype: int64
Mean: 1740.0
Max: 2200
Index of max: May


11.	Create a DataFrame with Student Name + 3 subject marks:Name | Math | Science | English

Then:

•	Print only the Math column

•	Print first 2 rows

•	Print the shape


In [97]:
df = pd.DataFrame({
"Name": ["Asha", "Vikram", "Ravi"],
"Math": [80, 90, 75],
"Science": [85, 88, 70],
"English": [78, 92, 82]
 })

print("Full DataFrame:\n", df)
print("Math column:\n", df['Math'])
print("First 2 rows:\n", df.head(2))
print("Shape:", df.shape)

Full DataFrame:
      Name  Math  Science  English
0    Asha    80       85       78
1  Vikram    90       88       92
2    Ravi    75       70       82
Math column:
 0    80
1    90
2    75
Name: Math, dtype: int64
First 2 rows:
      Name  Math  Science  English
0    Asha    80       85       78
1  Vikram    90       88       92
Shape: (3, 4)


12.	Using this DataFrame:

df = pd.DataFrame({
  
    "Account": [101,102,103,104],
    "Balance": [5000, 15000, 7000, 12000]
})

Filter rows where:

•	Balance > 8000

•	Balance between 6000 and 13000


In [108]:
df = pd.DataFrame({
    "Account": [101, 102, 103, 104],
    "Balance": [2000, 5000, 9000, 15000]
})
print("Original df: \n", df)
print("Balance > 8000:\n", df[df['Balance'] > 8000])
print("Balance between 6000 and 13000:\n",
      df[df['Balance'].between(6000, 13000)])


Original df: 
    Account  Balance
0      101     2000
1      102     5000
2      103     9000
3      104    15000
Balance > 8000:
    Account  Balance
2      103     9000
3      104    15000
Balance between 6000 and 13000:
    Account  Balance
2      103     9000
